version: '3.4'

services:
  eshopwebmvc:
    image: eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
  eshoppublicapi:
    image: eshoppublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile

